### ISSUE TITLE
File Finder Errors

### ISSUE THREAD

**Issue by cz2246** [ColumbiaJS/hw2#3]
In the .spec.js file for FileFinder, whether it throws an error when a file is not found is tested with:

```
describe('Given an extension with no files in the dir', function() {

  it('should call the callback with an error message', function(done) {
    FileFinder(process.cwd() + '/lib/csv-analyzer/', 'html', function (err, data) {
      expect(err.toString()).to.contain('Unable to find csv file');
      done();
    });
  });
});
```

What I don't get is that if we do not necessarily hard code 'csv' to the FileFinder module, how can we expect it to throw a error relating to a csv file when the extension we pass is .html? As a result, my code throws and ENOENT. So should we make a custom error? If so, how can we do that?

**Comment by levbrie** [comment]
@cz2246 That is a very good point!  To create a custom error in JavaScript, you simply use the new keyword with the Error object and provide a message as your argument:

``` js
var myError = new Error('This is a custom error message!');
```

In this case, you would pass that to a callback when the file isn't found.  But your point is well taken. The error should not be 'Unable to find html file'.  Since the FileFinder has the extension you're looking for passed in as an argument, you should be able to display it in your error message if you can't find it.  But of course, in the case of these tests, the two should match up!  I'll correct this for tomorrow and go over how to pull in the updated repos tomorrow in class.

Best,
Lev
